INCOMING: 2013-05-30
AUDIT_SESSION=849664187
VMODEM=/home/insulaudit/sessions/3-849664187/vmodem
SHELL=/bin/sh
BASE=/home/insulaudit/session
SSH_CLIENT=32.161.105.223 35466 22
FOO=BAR
PHR_REPO=
WORK_CONF=/home/insulaudit/sessions/3-849664187/conf
WORK_REMOTE=/home/insulaudit/sessions/3-849664187/remote.git
WORK_LOCAL=/home/insulaudit/sessions/3-849664187/local
BRANCH=audit/2013-05-30-3-849664187
USER=insulaudit
AUDIT_USER=ehwest
SESSION_CONFIG=/home/insulaudit/sessions/3-849664187/conf/audit.config
MAIL=/var/mail/insulaudit
PATH=/home/insulaudit/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
PWD=/home/insulaudit
LANG=en_US.UTF-8
HOME=/home/insulaudit
SHLVL=2
SSH_ORIGINAL_COMMAND=audit 849664187 3
LOGNAME=insulaudit
SSH_CONNECTION=32.161.105.223 35466 10.170.185.103 22
AUDIT_UID=3
WORK_BASE=/home/insulaudit/sessions/3-849664187
SESS_KEY=3-849664187
AUDIT_TOOL=audit
_=/usr/bin/env
mini.py --output /home/insulaudit/sessions/3-849664187/sugars.txt /home/insulaudit/sessions/3-849664187/vmodem
is open? True
 timeout: 0.5
Initial DISCONNECT
GETTING FIRMWARE INFO
FIRMWARE IS: P02.00.0025/05/07

read serial number
serial number: DLG8224ER

number of available records:
Traceback (most recent call last):
  File "/home/insulaudit/bin/mini.py", line 73, in <module>
    port = init(args)
  File "/home/insulaudit/bin/mini.py", line 43, in init
    max_records = mini.execute( lsultramini.ReadAvailableRecords( ) )
  File "/home/bewest/src/insulaudit/src/insulaudit/devices/lsultramini.py", line 196, in execute
    return command.decode( response )
  File "/home/bewest/src/insulaudit/src/insulaudit/devices/lsultramini.py", line 98, in decode
    return ls_int( data[ 2:4 ] )
  File "/home/bewest/src/insulaudit/src/insulaudit/devices/lsultramini.py", line 39, in ls_int
    return lib.BangInt( B )
  File "/home/bewest/src/insulaudit/src/insulaudit/lib.py", line 183, in BangInt
    ( x, y ) = ints
ValueError: need more than 0 values to unpack
